# docker-compose.yml
services:
  dev:
    container_name: rtems-llvm-dev
    image: rtems-llvm-latest
    build:
      context: .
    working_dir: /opt/rtems-llvm
    privileged: true
    volumes:
      - .:/opt/rtems-llvm
      - llvm-build:/opt/rtems-llvm/src/rtems-rsb/rtems/build
      - /dev/bus/usb:/dev/bus/usb
    command: sleep infinity
    stdin_open: true
    tty: true
    #   devices:
    #     - "/dev/ttyUSB0:/dev/ttyUSB0:rw"
    security_opt:
      - label=disable
      - apparmor=unconfined

volumes:
  llvm-build:
